### ISSUE TITLE
/topic/sizes fails with exception

### ISSUE THREAD

**Issue by behrica** [ddangelov/RESTful-Top2Vec#12]
Calling `/topc/sizes` with my model gives exception:
```
72.17.0.1:40920 - "GET /openapi.json HTTP/1.1" 200
172.17.0.1:40922 - "GET /docs HTTP/1.1" 200
172.17.0.1:40922 - "GET /openapi.json HTTP/1.1" 200
172.17.0.1:40924 - "GET /topics/sizes HTTP/1.1" 500
[2021-06-10 10:13:27 +0000] [29] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 390, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/fastapi/applications.py", line 149, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/applications.py", line 102, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.7/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.7/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 550, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/usr/local/lib/python3.7/site-packages/fastapi/routing.py", line 148, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "/usr/local/lib/python3.7/site-packages/fastapi/routing.py", line 101, in run_endpoint_function
    return await dependant.call(**values)
  File "/app/main.py", line 107, in get_topic_sizes
    topic_sizes, topic_nums = top2vec.get_topic_sizes()
  File "/usr/local/lib/python3.7/site-packages/top2vec/Top2Vec.py", line 384, in get_topic_sizes
    return np.array(self.topic_sizes.values), np.array(self.topic_sizes.index)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/generic.py", line 5272, in __getattr__
    if self._info_axis._can_hold_identifiers_and_holds_name(name):
  File "/usr/local/lib/python3.7/site-packages/pandas/core/generic.py", line 5272, in __getattr__
    if self._info_axis._can_hold_identifiers_and_holds_name(name):
  File "/usr/local/lib/python3.7/site-packages/pandas/core/generic.py", line 5272, in __getattr__
    if self._info_axis._can_hold_identifiers_and_holds_name(name):
  [Previous line repeated 480 more times]
  File "/usr/local/lib/python3.7/site-packages/pandas/core/generic.py", line 493, in _info_axis
    return getattr(self, self._info_axis_name)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/generic.py", line 5270, in __getattr__
    return object.__getattribute__(self, name)
  File "pandas/_libs/properties.pyx", line 63, in pandas._libs.properties.AxisProperty.__get__
  File "/usr/local/lib/python3.7/site-packages/pandas/core/generic.py", line 5270, in __getattr__
    return object.__getattribute__(self, name)
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by behrica** [comment]
The same model files works in python, 

calling topic_sizes, topic_nums = top2vec.get_topic_sizes()

**Comment by behrica** [comment]
My last comment is not correct,
In the Docker container "ddangelov/restful-top2vec"  I get the same error message inside a python command line then above with my model file.

**Comment by behrica** [comment]
Nevertheless it **does work** in the virtual environment I use on my local PC.

So the error  depends on which libraries are installed.

If you share here the Dockerfile, I could maybe investigate further.

**Comment by behrica** [comment]
I found the Dockerfile..

**Comment by behrica** [comment]
I applied locally all pending PRs which upgrade the versions, and that fixed the issue.
